### ISSUE TITLE
Only two items are in the datawarehouse

### ISSUE THREAD

**Issue by Vansir01** [Grasia/dao-analyzer#103]
I tried to acquire the data from DAO analyzer, but when I finished the "python3 -m cache_scripts", only two items occurred named ".cs.lock" and ".lock". So I would like to find out the reason. Thank you!

**Comment by daviddavo** [comment]
Do you have any logs? An error on the terminal should have appeared.

**Comment by Vansir01** [comment]
> 
Thanks for your response.

I'm confused about the two ".lock" files (See the attached image). 
There should be a lot of files after the "python3 -m cache_scripts“ command, right? 

![image](https://user-images.githubusercontent.com/53443283/190457647-e6937164-1d1c-44e6-bbff-3c0c0119e4da.png)

**Comment by daviddavo** [comment]
We have not tested the application on Windows. I'll try to fix it for next release. In the meantime, you can use windows for linux subsystem, or docker.

**Comment by daviddavo** [comment]
The dataset is now available on [Kaggle](https://www.kaggle.com/datasets/daviddavo/dao-analyzer) and I couldn't reproduce the error
