### ISSUE TITLE
The same DAO is displayed several times when selecting the Daohaus platform

### ISSUE THREAD

**Issue by mcvaliente** [Grasia/dao-analyzer#27]
![image](https://user-images.githubusercontent.com/60616466/134482533-a72a3134-6038-46c9-9014-5a6b8c64f69e.png)

**Comment by daviddavo** [comment]
They seem to be different DAOs, with different members, proposals, etc...

![image](https://user-images.githubusercontent.com/10263941/134875536-d5421a04-c995-4e1a-8592-c6f301fd3205.png)

This seems to be another problem that would be solved with a UX overhaul. I was thinking of a table that lets you filter in some colums (like by network mainnet/xdai) and sorting on others (name, proposals, last activity, etc.).

**Comment by daviddavo** [comment]
Until the selector UX is completely changed, this is a temporary fix:

![image](https://user-images.githubusercontent.com/10263941/135056859-47672e6d-43cd-4032-8e06-e3a135fa970f.png)
