### ISSUE TITLE
Add the number of version deployed in the footer

### ISSUE THREAD

**Issue by javiag** [Grasia/dao-analyzer#51]
In the left-hand side of the footer, the application currently shows "Follow us on Github".  

I think we could add the version deployed such as "DAO-analyzer vX.Y.Z. Follow us on Github"

**Comment by daviddavo** [comment]
Maybe setting the version number while building the docker file, and getting that version number from git. If it's a tag, it'll display the version number, while if it is a regular commit, it would display the commit hash.

This can be done running `git describe`

> The command finds the most recent tag that is reachable from a commit. If the tag points to the commit, then only the tag is shown. Otherwise, it suffixes the tag name with the
> number of additional commits on top of the tagged object and the abbreviated object name of the most recent commit. The result is a "human-readable" object name which can also be
> used to identify the commit to other git commands.

```
$ git describe --tags
v0.7.1-1-g5eb216b
```

**Comment by javiag** [comment]
Sounds great :)

**Comment by daviddavo** [comment]
![image](https://user-images.githubusercontent.com/10263941/156191827-a36341c5-26ef-4a0c-8960-85db1487961f.png)

Done and live!
