### ISSUE TITLE
Show datawarehouse last update datetime

### ISSUE THREAD

**Issue by daviddavo** [Grasia/dao-analyzer#54]
Currently we show just the date because the dw was updated every few weeks. Now that it's updated daily, it would be useful to show the update time as well.

**Comment by javiag** [comment]
We should show the time zone.

**Comment by daviddavo** [comment]
How about this?

(ISO 8601 style)

![image](https://user-images.githubusercontent.com/10263941/160111094-73a8a19c-32f3-4f62-8ebf-8781fdc2af87.png)

**Comment by javiag** [comment]
I think that this is not the best way for humans. At least for those that are not computer scientists :D 

I'd suggest something easier to read:

Sep 25, 2022 at 14:31 UTC

or 

Sep 25, 2022 at 2:31 PM UTC

**Comment by daviddavo** [comment]
https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior

Okay, using the following strf

```
>>> datetime.now(timezone.utc).replace(day=3).strftime("%b %-d, %Y at %H:%M %Z")
'Mar 3, 2022 at 12:09 UTC'
```
