### ISSUE TITLE
Show the "plot sections" as tabs 

### ISSUE THREAD

**Issue by javiag** [Grasia/dao-analyzer#64]
Instead of having one long page of plots with different sections, it would be nice to have different tabs (each of the current sections would be a tab).

We have to see how to make it, and perhaps ask our designer for feedback. But I feel it would make the webapp more understandable (people would know what is possible to see more easily).

**Comment by daviddavo** [comment]
Plotly has native support for tabs: https://dash.plotly.com/dash-core-components/tabs

**Comment by daviddavo** [comment]
![image](https://user-images.githubusercontent.com/10263941/160373997-d3e7b793-3ff5-46ad-970b-1e8d73d3625d.png)

Feedback? @javiag

**Comment by javiag** [comment]
Looks great!
