### ISSUE TITLE
Create "about" page

### ISSUE THREAD

**Issue by javiag** [Grasia/dao-analyzer#69]
I think we should briefly explain to humans what DAO-analyzer does, what it shows, where the data come from... and also how it does it, this last part would be a brief explanation for techy humans.

We could create a collaborative document and ask for feedback from our colleagues.

> ## Note:
> Drafting of the text will continue on [Google Drive](https://docs.google.com/document/d/1ojBMyzhMVbEi1ANLRZef8nfGJcBJ3w6y2kyhRH7Gz38/edit?usp=sharing)

- [x] Write the document
- [x] Put link in the footer
- [x] Check that ABOUT.md is distributed in the package and /about is visible in the docker image and python package

**Comment by daviddavo** [comment]
We have to ask Elena where to put the link to the about page

**Comment by daviddavo** [comment]
To make it easier to modify, we can use the `Markdown` component

- https://dash.plotly.com/dash-core-components/markdown

We could have an `ABOUT.md` file in our project root, and then use it too for DAO-Analyzer

**Comment by daviddavo** [comment]
Work in progress

![image](https://user-images.githubusercontent.com/10263941/161255010-9ab3bf4d-c6cb-4d90-8470-b13bb5a712ca.png)

**Comment by daviddavo** [comment]
Waiting for the text to be written

**Comment by daviddavo** [comment]
Drafting of the text will continue on [Google Drive](https://docs.google.com/document/d/1ojBMyzhMVbEi1ANLRZef8nfGJcBJ3w6y2kyhRH7Gz38/edit?usp=sharing)

**Comment by javiag** [comment]
I reviewed the text. I think that we got ready the first version :)
