### ISSUE TITLE
Archive a copy of the data warehouse in a public repository 

### ISSUE THREAD

**Issue by javiag** [Grasia/dao-analyzer#71]
Archiving a copy of the data warehouse in a public repository would be useful for several things, including easing deployment of dao-analyzer (as it would not require creating the data warehouse from scratch, but just updating it) and improving the persistence of the project in the long run (if the subgraphs are not deployed, if somo blockchain networks are not operative...).

We could go for a private platform, such as Kaggle, that will give a lot of visibility to the data, but we also should try for public initiatives to ensure again accessibility in the long run. Before deciding, we should read the recommendations here:
https://www.openaire.eu/opendatapilot-repository-guide

**Comment by daviddavo** [comment]
> If available, use an institutional research data repository, or your research group’s established data management facilities.

Does the UCM have any kind of data repository?

**Comment by javiag** [comment]
I don't think so, but, ask, please.

**Comment by daviddavo** [comment]
Jose Luis (director of OTEA) told me that we can use UCM's e-prints for that

- [Política institucional de Acceso Abierto a la producción científica y académica de la UCM](https://biblioteca.ucm.es/data/cont/docs/60-2014-05-27-politica_acceso_abierto_20140527.pdf)
- https://eprints.ucm.es/view/types/dataset.html

**Comment by daviddavo** [comment]
Done in [Kaggle](https://www.kaggle.com/datasets/daviddavo/dao-analyzer) and [Zenodo](https://zenodo.org/record/7750956)
