### ISSUE TITLE
DAO summary info

### ISSUE THREAD

**Issue by javiag** [Grasia/dao-analyzer#73]
[DAO-ANALYZER_v2_2.pdf](https://github.com/Grasia/dao-analyzer/files/8571057/DAO-ANALYZER_v2_2.pdf)
Besides the name, network and address, we could show some extra info that summarizes the DAO. 

Which things we should show require careful thinking, but here come some ideas:
- Number of members:
- Creation date:
- Active in the last X months (use the same number of months X used in the DAOfilter):
- Treasury in $
- Total number of proposals (% of proposals passed)

We can deploy the first version and later on refine it adding or removing info.

We need Elena's help with the layout. 

- [x] Make layout
- [x] Pass creation date to layout
- [x] Pass members to layout
- [x] Pass treasury to layout
- [x] Pass proposals to layout
- [x] Pass members variation to layout
- [x] Pass proposals variation to layout
- [x] Implement on Aragon
- [x] Implement on Daohaus
- [x] Implement on Daostack

> Note: to be able to implement faster, I got rid of the following features
> - The difference is relative (already calculated) instead of absolute
> - Loading animations on things

**Comment by daviddavo** [comment]
What do we show when there is no DAO selected?

**Comment by javiag** [comment]
Perhaps, the DAO ecosystem stats in the following (very similar) terms: 

- Number of DAOs 
- Number of members 
- Treasury in $
- Total number of proposals (% of proposals passed)

This should be easy because is just an aggregation of the individual stats (of course, the percentage of proposals passed is an aggregation of the number of proposals passed and the total number of proposals, not the average of the percentages).

**Comment by daviddavo** [comment]
This is how's going with the colors in the PDF (we can change them later).

> Note: The data is still unconnected

![image](https://user-images.githubusercontent.com/10263941/165727441-6134bd20-50cc-4b56-888d-167689c38a3c.png)

**Comment by daviddavo** [comment]
Hm... There is a small problem

Not every platform has "Members", and not every platform has "Proposals". So the current approach doesn't suit it well...

**Comment by daviddavo** [comment]
Done, and merged into develop.

It works by adding a DataPoint to the controller, like how the charts work. The datapoint then is updated by a modified chart controller. This means that the DataPoint is just _another_ view of a data chart. If we wanted to add, for example, the total number of proposals, we would have to add new charts
