### ISSUE TITLE
Improve summary card

### ISSUE THREAD

**Issue by daviddavo** [Grasia/dao-analyzer#83]
- [x] Add total members datapoint
  - [x] Daostack
  - [x] Aragon
      - [x] Create graph with total members
  - [x] Daohaus
- [x] Fix creation date on DAOstack
- [x] Move Created to DAO Info table
- [x] Add last activity date
- [x] Move last activity date to the right
- [x] Show absolute value instead of relative

**Comment by daviddavo** [comment]
I've made the "Last activity" thing on the card header another "view" for the activity graph (the same as with the summary points).

Nevertheless, I think we should make the Organization List Data Access Object a bit more heavyweight (loading not only organizations.csv, but also activity.csv), and include some data like `lastActive` in the Organization Data Transfer Object (used, for example, to create the Dropdown and the table with the DAO info). This should help us make the Select a DAO dropdown filterable on the front-end.

I'll keep this issue blocked until we change the OrganizationListDAO

## A DAO without any activity

![image](https://user-images.githubusercontent.com/10263941/169700799-d68ef02a-5d1c-465b-ad12-b5ec0bd6a899.png)

## A DAO with activity

![image](https://user-images.githubusercontent.com/10263941/169700875-74f4018a-6ede-4430-baa7-232a2e9fc744.png)

**Comment by javiag** [comment]
Regarding the inclusion of more info in the OrganizationListDAO, I think it's the way to go. 

So far, we don't know if we will have a DAO table anytime soon, but definitely we will need that info for including some filters in the selection process.

Please, go for it.
