### ISSUE TITLE
Add some equality stats to the summary

### ISSUE THREAD

**Issue by daviddavo** [Grasia/dao-analyzer#84]
The idea would be to do something like this for every DAO

![image](https://user-images.githubusercontent.com/10263941/170448921-5d2fac68-5e4d-43ca-80d9-d4aa0413140f.png)

- [x] Modify the layout
- [x] Create a DTO for the stat, and add it to the organization
- [x] Calculate the stats
  - [x] Aragon
    - [x] Proposals
    - [x] Votes
  - [x] Daostack
    - [x] Proposals
    - [x] Votes
  - [x] Daohaus
    - [x] Proposals
    - [x] Votes
- [x] Use TEXT[] instead of hardcoding it

**Comment by daviddavo** [comment]
In Aragon tables, there exists a field called `creator`. The problem is, that creator is usually an AppProxy contract

For example, with **AAvegotchi**, every proposal that was created has the following format:

| **network** | **id** | **orgAddress** | **appAddress** | **creator**
|---------|-------|-----------|-----|-----|
| mainnet | (appAddress)-(counter) | [0x054086d40cf8fd5bf6200eda7f9c6877b0302dd1](https://etherscan.io/address/0x054086d40cf8fd5bf6200eda7f9c6877b0302dd1#code) | [0x93cf86a83baa323407857c0a25e768869e12c721](https://etherscan.io/address/0x93cf86a83baa323407857c0a25e768869e12c721#code) | [0x8efea71b63db02c00229794d90ec4ba8ecd4ea81](https://etherscan.io/address/0x8efea71b63db02c00229794d90ec4ba8ecd4ea81#code) | 

Both `appAddress` and `creator` are AppProxyUpgradeable contracts

`0x93...` (appAddress) is the voting app, and `0x8efea...` (creator) happens to be the [Tokens/AGT app](https://client.aragon.org/#/aavegotchi/0x8efea71b63db02c00229794d90ec4ba8ecd4ea81/)

If we go to its [voting app](https://client.aragon.org/#/aavegotchi/0x93cf86a83baa323407857c0a25e768869e12c721/), It is reflected with a _Finance_ icon

Do these "Finance" things get created automatically? Or is there some user behind creating the proposal? How do we get that user? It's not displayed on Aragon Client, so I don't think there is a method to obtain it.

**Comment by javiag** [comment]
Mmmm, it is strange. It should be somewhere.

We should ask our colleagues at 1Hive. They will know how to retrieve that info.

**Comment by javiag** [comment]
By the way, I assume that the participation stat on "voting" can be computed. So at least, we should show that :)

**Comment by daviddavo** [comment]
Same problem, lots of DAOs show 0% of members voted...

I've just noticed that "members" are just holders. So people that are no longer members won't be counted?

**Comment by javiag** [comment]
See this link: 

https://thegraph.com/hosted-service/subgraph/1hive/aragon-voting-mainnet


gql
{
  votes(first: 5) {
    orgAddress
    appAddress
    creator
    originalCreator
  }
}

originalCreator is the answer for both votes and proposals :)

**Comment by daviddavo** [comment]
In the case of Aavegotchi, every proposal has been created by the same person. Because of this, the text displayed is "0% of members have created a proposal", which doesn't say a lot...

Maybe we should think about adding other texts or changing the ones we have now

**Comment by javiag** [comment]
Well, I don't think that the exception should make us change the general behavior.

Some potential solutions:
- Leave it as it is, 
- Add a decimal number just for the case of zero
- Use the absolute number instead of the percentage just for the case of zero.
- Add the absolute number always in parentheses.

Let me know what you think.

**Comment by daviddavo** [comment]
I was thinking of adding more resolution in the case of zero (adding decimal numbers)
